# Generated by Django 4.1.2 on 2022-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0002_alter_informacion_usuario_fecha_nacimiento_picina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria_picina',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='picina',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
