# Generated by Django 4.1.2 on 2022-11-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0004_paquete_picina_añadido_paquete_picina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suministro_picina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_inventario', models.IntegerField()),
                ('picina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sara.picina')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=30)),
                ('picina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sara.picina')),
            ],
        ),
    ]
