# Generated by Django 4.1.2 on 2022-11-10 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0006_alter_paquete_picina_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='picina',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paquete_picina',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
