# Generated by Django 4.1.3 on 2022-11-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0007_picina_descripcion_alter_paquete_picina_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
                ('picina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sara.picina')),
            ],
        ),
    ]
