# Generated by Django 4.1.3 on 2022-11-24 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0010_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora_final',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora_inicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='rentero',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
