# Generated by Django 4.1.3 on 2022-11-25 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sara', '0012_rename_fecha_cita_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato_rentado',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato_rentado',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato_rentado',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato_rentado',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
